# Generated by Django 5.0.7 on 2024-07-12 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaitList',
            new_name='WhiteList',
        ),
        migrations.CreateModel(
            name='SSHSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('waktu', models.TimeField(auto_now_add=True)),
                ('protocol', models.CharField(max_length=100)),
                ('user_login', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=10)),
                ('ip', models.GenericIPAddressField()),
                ('id_idpslog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.idpslog')),
            ],
        ),
    ]
