# Generated by Django 5.0.7 on 2024-07-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sshsuccess_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshsuccess',
            name='port',
            field=models.CharField(max_length=10),
        ),
    ]
