# Generated by Django 5.0.7 on 2024-07-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sshsuccess_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
